spring:
  datasource:
      url: jdbc:mysql://localhost:3306/work-forces?createDatabaseIfNotExist=true
      password:
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jooq:
    sql-dialect: true

server:
  port: 8082
